apiVersion: v1
kind: PersistentVolume
metadata:
  name: 10gi-01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /exports/pvs/10gi-01
    server: nfs.ocp4.lab
  persistentVolumeReclaimPolicy: Retain