apiVersion: v1
kind: PersistentVolume
metadata:
  name: 5gi-01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /exports/pvs/5gi-01
    server: nfs.ocp4.lab
  persistentVolumeReclaimPolicy: Retain