apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /exports/registry
    server: nfs.ocp4.lab
  persistentVolumeReclaimPolicy: Retain